apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
            - containerPort: 8920
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-media
              mountPath: /media
      volumes:
        - name: jellyfin-config
          hostPath:
            path: /mnt/data1/jellyfin/config
            type: DirectoryOrCreate
        - name: jellyfin-media
          hostPath:
            path: /mnt/data1/jellyfin/media
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: NodePort
  selector:
    app: jellyfin
  ports:
    - port: 443
      targetPort: 8096
      nodePort: 30003
